### ISSUE TITLE
"TypeError: ZU.XRegExp is not a constructor" when trying to export bibtex

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server-v2#34] opened 2018-08-15 10:55 UTC
```(3)(+0000000): Translators initialized with 523 loaded

(3)(+0000004): Listening on 0.0.0.0:1969

(4)(+0055140): Translate: Binding sandbox to http://www.example.com/

(4)(+0000001): Translate: Parsing code for BibTeX (9cb70025-a888-4a29-a210-93ec52da40d4, 2018-03-03 13:10:16)

(3)(+0000004): Translate: Beginning translation with BibTeX

(3)(+0000003): TypeError: ZU.XRegExp is not a constructor

    TypeError: ZU.XRegExp is not a constructor
        at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
        at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
        at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

(2)(+0000000): Translate: Translation using BibTeX failed: 
TypeError: ZU.XRegExp is not a constructor

TypeError: ZU.XRegExp is not a constructor
    at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
    at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
    at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

(5)(+0000001): Translate: Running handler 0 for error

(5)(+0000000): Translate: Running handler 0 for done

(node:2997) UnhandledPromiseRejectionWarning: TypeError: ZU.XRegExp is not a constructor
    at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
    at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
    at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 85)
(node:2997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(4)(+0003467): Translate: Binding sandbox to http://www.example.com/

(4)(+0000001): Translate: Parsing code for BibTeX (9cb70025-a888-4a29-a210-93ec52da40d4, 2018-03-03 13:10:16)

(3)(+0000005): Translate: Beginning translation with BibTeX

(3)(+0000001): TypeError: ZU.XRegExp is not a constructor

    TypeError: ZU.XRegExp is not a constructor
        at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
        at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
        at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

(2)(+0000000): Translate: Translation using BibTeX failed: 
TypeError: ZU.XRegExp is not a constructor

TypeError: ZU.XRegExp is not a constructor
    at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
    at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
    at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

(5)(+0000000): Translate: Running handler 0 for error

(5)(+0000001): Translate: Running handler 0 for done

(node:2997) UnhandledPromiseRejectionWarning: TypeError: ZU.XRegExp is not a constructor
    at doExport (eval at <anonymous> (/home/marielle/code/translation-server-v2/src/translation/sandboxManager.js:68:4), <anonymous>:1234:19)
    at Zotero.Translate.Export.rest (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1389:49)
    at loadPromise.then (/home/marielle/code/translation-server-v2/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1379:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 90)
```

**Comment by dstillman** [comment] 2018-08-15 11:03
Dupe of https://github.com/zotero/translation-server-v2/issues/5 (but thanks)

**Closed by dstillman** 2018-08-15 11:03 UTC
